# Generated by Django 6.1 on 2026-08-12 13:26

import EcommerceApp.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', EcommerceApp.managers.UserManager()),
            ],
        ),
    ]
